server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: server-one
eureka:
  client:
    service-url:
      defaultZone: http://server1:11111/eureka
